// Code generated by protoc-gen-go. DO NOT EDIT.
// source: stream.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ID struct {
	// net_key of the peer (we no longer use the public key as the peer ID, but use it to verify messages)
	NetKey []byte `protobuf:"bytes,1,opt,name=net_key,json=netKey,proto3" json:"net_key,omitempty"`
	// address is the network address of the peer
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	// id is the computed hash of the net key
	Id                   []byte   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ID) Reset()         { *m = ID{} }
func (m *ID) String() string { return proto.CompactTextString(m) }
func (*ID) ProtoMessage()    {}
func (*ID) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb17ef3f514bfe54, []int{0}
}

func (m *ID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ID.Unmarshal(m, b)
}
func (m *ID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ID.Marshal(b, m, deterministic)
}
func (m *ID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ID.Merge(m, src)
}
func (m *ID) XXX_Size() int {
	return xxx_messageInfo_ID.Size(m)
}
func (m *ID) XXX_DiscardUnknown() {
	xxx_messageInfo_ID.DiscardUnknown(m)
}

var xxx_messageInfo_ID proto.InternalMessageInfo

func (m *ID) GetNetKey() []byte {
	if m != nil {
		return m.NetKey
	}
	return nil
}

func (m *ID) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *ID) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

type Message struct {
	Message []byte `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// Sender's address and net key.
	Sender *ID `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	// Sender's signature of message.
	Signature []byte `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	// request_nonce is the request/response ID. Null if ID associated to a message is not a request/response.
	RequestNonce uint64 `protobuf:"varint,4,opt,name=request_nonce,json=requestNonce,proto3" json:"request_nonce,omitempty"`
	// message_nonce is the sequence ID.
	MessageNonce uint64 `protobuf:"varint,5,opt,name=message_nonce,json=messageNonce,proto3" json:"message_nonce,omitempty"`
	// reply_flag indicates this is a reply to a request
	ReplyFlag bool `protobuf:"varint,6,opt,name=reply_flag,json=replyFlag,proto3" json:"reply_flag,omitempty"`
	// opcode specifies the message type
	Opcode uint32 `protobuf:"varint,7,opt,name=opcode,proto3" json:"opcode,omitempty"`
	// dial_address is the outgoing address for a udp connection
	DialAddress          string   `protobuf:"bytes,8,opt,name=dial_address,json=dialAddress,proto3" json:"dial_address,omitempty"`
	NetID                uint32   `protobuf:"varint,9,opt,name=netID,proto3" json:"netID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb17ef3f514bfe54, []int{1}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *Message) GetSender() *ID {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *Message) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *Message) GetRequestNonce() uint64 {
	if m != nil {
		return m.RequestNonce
	}
	return 0
}

func (m *Message) GetMessageNonce() uint64 {
	if m != nil {
		return m.MessageNonce
	}
	return 0
}

func (m *Message) GetReplyFlag() bool {
	if m != nil {
		return m.ReplyFlag
	}
	return false
}

func (m *Message) GetOpcode() uint32 {
	if m != nil {
		return m.Opcode
	}
	return 0
}

func (m *Message) GetDialAddress() string {
	if m != nil {
		return m.DialAddress
	}
	return ""
}

func (m *Message) GetNetID() uint32 {
	if m != nil {
		return m.NetID
	}
	return 0
}

type Ping struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ping) Reset()         { *m = Ping{} }
func (m *Ping) String() string { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()    {}
func (*Ping) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb17ef3f514bfe54, []int{2}
}

func (m *Ping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ping.Unmarshal(m, b)
}
func (m *Ping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ping.Marshal(b, m, deterministic)
}
func (m *Ping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ping.Merge(m, src)
}
func (m *Ping) XXX_Size() int {
	return xxx_messageInfo_Ping.Size(m)
}
func (m *Ping) XXX_DiscardUnknown() {
	xxx_messageInfo_Ping.DiscardUnknown(m)
}

var xxx_messageInfo_Ping proto.InternalMessageInfo

type Pong struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pong) Reset()         { *m = Pong{} }
func (m *Pong) String() string { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()    {}
func (*Pong) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb17ef3f514bfe54, []int{3}
}

func (m *Pong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pong.Unmarshal(m, b)
}
func (m *Pong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pong.Marshal(b, m, deterministic)
}
func (m *Pong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pong.Merge(m, src)
}
func (m *Pong) XXX_Size() int {
	return xxx_messageInfo_Pong.Size(m)
}
func (m *Pong) XXX_DiscardUnknown() {
	xxx_messageInfo_Pong.DiscardUnknown(m)
}

var xxx_messageInfo_Pong proto.InternalMessageInfo

type LookupNodeRequest struct {
	Target               *ID      `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LookupNodeRequest) Reset()         { *m = LookupNodeRequest{} }
func (m *LookupNodeRequest) String() string { return proto.CompactTextString(m) }
func (*LookupNodeRequest) ProtoMessage()    {}
func (*LookupNodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb17ef3f514bfe54, []int{4}
}

func (m *LookupNodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LookupNodeRequest.Unmarshal(m, b)
}
func (m *LookupNodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LookupNodeRequest.Marshal(b, m, deterministic)
}
func (m *LookupNodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LookupNodeRequest.Merge(m, src)
}
func (m *LookupNodeRequest) XXX_Size() int {
	return xxx_messageInfo_LookupNodeRequest.Size(m)
}
func (m *LookupNodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LookupNodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LookupNodeRequest proto.InternalMessageInfo

func (m *LookupNodeRequest) GetTarget() *ID {
	if m != nil {
		return m.Target
	}
	return nil
}

type LookupNodeResponse struct {
	Peers                []*ID    `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LookupNodeResponse) Reset()         { *m = LookupNodeResponse{} }
func (m *LookupNodeResponse) String() string { return proto.CompactTextString(m) }
func (*LookupNodeResponse) ProtoMessage()    {}
func (*LookupNodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb17ef3f514bfe54, []int{5}
}

func (m *LookupNodeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LookupNodeResponse.Unmarshal(m, b)
}
func (m *LookupNodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LookupNodeResponse.Marshal(b, m, deterministic)
}
func (m *LookupNodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LookupNodeResponse.Merge(m, src)
}
func (m *LookupNodeResponse) XXX_Size() int {
	return xxx_messageInfo_LookupNodeResponse.Size(m)
}
func (m *LookupNodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LookupNodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LookupNodeResponse proto.InternalMessageInfo

func (m *LookupNodeResponse) GetPeers() []*ID {
	if m != nil {
		return m.Peers
	}
	return nil
}

type Bytes struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Bytes) Reset()         { *m = Bytes{} }
func (m *Bytes) String() string { return proto.CompactTextString(m) }
func (*Bytes) ProtoMessage()    {}
func (*Bytes) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb17ef3f514bfe54, []int{6}
}

func (m *Bytes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bytes.Unmarshal(m, b)
}
func (m *Bytes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bytes.Marshal(b, m, deterministic)
}
func (m *Bytes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bytes.Merge(m, src)
}
func (m *Bytes) XXX_Size() int {
	return xxx_messageInfo_Bytes.Size(m)
}
func (m *Bytes) XXX_DiscardUnknown() {
	xxx_messageInfo_Bytes.DiscardUnknown(m)
}

var xxx_messageInfo_Bytes proto.InternalMessageInfo

func (m *Bytes) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Keepalive struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Keepalive) Reset()         { *m = Keepalive{} }
func (m *Keepalive) String() string { return proto.CompactTextString(m) }
func (*Keepalive) ProtoMessage()    {}
func (*Keepalive) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb17ef3f514bfe54, []int{7}
}

func (m *Keepalive) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Keepalive.Unmarshal(m, b)
}
func (m *Keepalive) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Keepalive.Marshal(b, m, deterministic)
}
func (m *Keepalive) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Keepalive.Merge(m, src)
}
func (m *Keepalive) XXX_Size() int {
	return xxx_messageInfo_Keepalive.Size(m)
}
func (m *Keepalive) XXX_DiscardUnknown() {
	xxx_messageInfo_Keepalive.DiscardUnknown(m)
}

var xxx_messageInfo_Keepalive proto.InternalMessageInfo

type KeepaliveResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeepaliveResponse) Reset()         { *m = KeepaliveResponse{} }
func (m *KeepaliveResponse) String() string { return proto.CompactTextString(m) }
func (*KeepaliveResponse) ProtoMessage()    {}
func (*KeepaliveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb17ef3f514bfe54, []int{8}
}

func (m *KeepaliveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeepaliveResponse.Unmarshal(m, b)
}
func (m *KeepaliveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeepaliveResponse.Marshal(b, m, deterministic)
}
func (m *KeepaliveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeepaliveResponse.Merge(m, src)
}
func (m *KeepaliveResponse) XXX_Size() int {
	return xxx_messageInfo_KeepaliveResponse.Size(m)
}
func (m *KeepaliveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_KeepaliveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_KeepaliveResponse proto.InternalMessageInfo

type Disconnect struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Disconnect) Reset()         { *m = Disconnect{} }
func (m *Disconnect) String() string { return proto.CompactTextString(m) }
func (*Disconnect) ProtoMessage()    {}
func (*Disconnect) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb17ef3f514bfe54, []int{9}
}

func (m *Disconnect) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Disconnect.Unmarshal(m, b)
}
func (m *Disconnect) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Disconnect.Marshal(b, m, deterministic)
}
func (m *Disconnect) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Disconnect.Merge(m, src)
}
func (m *Disconnect) XXX_Size() int {
	return xxx_messageInfo_Disconnect.Size(m)
}
func (m *Disconnect) XXX_DiscardUnknown() {
	xxx_messageInfo_Disconnect.DiscardUnknown(m)
}

var xxx_messageInfo_Disconnect proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ID)(nil), "protobuf.ID")
	proto.RegisterType((*Message)(nil), "protobuf.Message")
	proto.RegisterType((*Ping)(nil), "protobuf.Ping")
	proto.RegisterType((*Pong)(nil), "protobuf.Pong")
	proto.RegisterType((*LookupNodeRequest)(nil), "protobuf.LookupNodeRequest")
	proto.RegisterType((*LookupNodeResponse)(nil), "protobuf.LookupNodeResponse")
	proto.RegisterType((*Bytes)(nil), "protobuf.Bytes")
	proto.RegisterType((*Keepalive)(nil), "protobuf.Keepalive")
	proto.RegisterType((*KeepaliveResponse)(nil), "protobuf.KeepaliveResponse")
	proto.RegisterType((*Disconnect)(nil), "protobuf.Disconnect")
}

func init() { proto.RegisterFile("stream.proto", fileDescriptor_bb17ef3f514bfe54) }

var fileDescriptor_bb17ef3f514bfe54 = []byte{
	// 406 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x51, 0xd1, 0x8a, 0x13, 0x31,
	0x14, 0x65, 0x66, 0xdb, 0x69, 0xe7, 0x76, 0x56, 0xd8, 0x28, 0x6b, 0x40, 0x85, 0x31, 0x8a, 0xcc,
	0xd3, 0x3c, 0xe8, 0x8b, 0x3e, 0x5a, 0x8a, 0x52, 0x56, 0x4b, 0x99, 0x1f, 0x28, 0xd9, 0xe6, 0xee,
	0x10, 0x76, 0x36, 0x89, 0x49, 0x2a, 0xf4, 0x73, 0xfc, 0x53, 0x99, 0x24, 0xa3, 0x0b, 0xfb, 0x94,
	0x7b, 0xce, 0x3d, 0x27, 0x27, 0x9c, 0x40, 0xe5, 0xbc, 0x45, 0xfe, 0xd0, 0x1a, 0xab, 0xbd, 0x26,
	0xcb, 0x70, 0xdc, 0x9e, 0xee, 0xd8, 0x77, 0xc8, 0xb7, 0x1b, 0xf2, 0x12, 0x16, 0x0a, 0xfd, 0xe1,
	0x1e, 0xcf, 0x34, 0xab, 0xb3, 0xa6, 0xea, 0x0a, 0x85, 0xfe, 0x06, 0xcf, 0x84, 0xc2, 0x82, 0x0b,
	0x61, 0xd1, 0x39, 0x9a, 0xd7, 0x59, 0x53, 0x76, 0x13, 0x24, 0xcf, 0x20, 0x97, 0x82, 0x5e, 0x04,
	0x75, 0x2e, 0x05, 0xfb, 0x93, 0xc3, 0xe2, 0x27, 0x3a, 0xc7, 0x7b, 0x1c, 0x5d, 0x0f, 0x71, 0x4c,
	0xd7, 0x4d, 0x90, 0xbc, 0x87, 0xc2, 0xa1, 0x12, 0x68, 0xc3, 0x75, 0xab, 0x8f, 0x55, 0x3b, 0xbd,
	0xa4, 0xdd, 0x6e, 0xba, 0xb4, 0x23, 0xaf, 0xa1, 0x74, 0xb2, 0x57, 0xdc, 0x9f, 0x2c, 0xa6, 0x88,
	0xff, 0x04, 0x79, 0x07, 0x97, 0x16, 0x7f, 0x9d, 0xd0, 0xf9, 0x83, 0xd2, 0xea, 0x88, 0x74, 0x56,
	0x67, 0xcd, 0xac, 0xab, 0x12, 0xb9, 0x1b, 0xb9, 0x51, 0x94, 0x32, 0x93, 0x68, 0x1e, 0x45, 0x89,
	0x8c, 0xa2, 0x37, 0x00, 0x16, 0xcd, 0x70, 0x3e, 0xdc, 0x0d, 0xbc, 0xa7, 0x45, 0x9d, 0x35, 0xcb,
	0xae, 0x0c, 0xcc, 0xb7, 0x81, 0xf7, 0xe4, 0x1a, 0x0a, 0x6d, 0x8e, 0x5a, 0x20, 0x5d, 0xd4, 0x59,
	0x73, 0xd9, 0x25, 0x44, 0xde, 0x42, 0x25, 0x24, 0x1f, 0x0e, 0x53, 0x33, 0xcb, 0xd0, 0xcc, 0x6a,
	0xe4, 0xbe, 0xa6, 0x76, 0x5e, 0xc0, 0x5c, 0xa1, 0xdf, 0x6e, 0x68, 0x19, 0x9c, 0x11, 0xb0, 0x02,
	0x66, 0x7b, 0xa9, 0xfa, 0x70, 0x6a, 0xd5, 0xb3, 0x2f, 0x70, 0xf5, 0x43, 0xeb, 0xfb, 0x93, 0xd9,
	0x69, 0x81, 0x5d, 0x7c, 0xfe, 0x58, 0x91, 0xe7, 0xb6, 0x47, 0x1f, 0xba, 0x7b, 0x52, 0x51, 0xdc,
	0xb1, 0xcf, 0x40, 0x1e, 0x5b, 0x9d, 0xd1, 0xca, 0x21, 0x61, 0x30, 0x37, 0x88, 0xd6, 0xd1, 0xac,
	0xbe, 0x78, 0x62, 0x8d, 0x2b, 0xf6, 0x0a, 0xe6, 0xeb, 0xb3, 0x47, 0x47, 0x08, 0xcc, 0x04, 0xf7,
	0x3c, 0x7d, 0x51, 0x98, 0xd9, 0x0a, 0xca, 0x1b, 0x44, 0xc3, 0x07, 0xf9, 0x1b, 0xd9, 0x73, 0xb8,
	0xfa, 0x07, 0xa6, 0x08, 0x56, 0x01, 0x6c, 0xa4, 0x3b, 0x6a, 0xa5, 0xf0, 0xe8, 0xd7, 0x1f, 0xe0,
	0x5a, 0xdb, 0xbe, 0x35, 0x68, 0x07, 0xa9, 0x5a, 0xa5, 0xa5, 0xc3, 0x98, 0xb9, 0x86, 0xdd, 0x08,
	0xf6, 0xe3, 0xbc, 0xcf, 0x6e, 0x8b, 0x40, 0x7e, 0xfa, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x66, 0xb0,
	0x03, 0x55, 0x87, 0x02, 0x00, 0x00,
}
